let data = [
    // paste CSV to json data here
        ["ART/CULTURE",25,10,"A","ACTOR, COMEDIAN AND CIRCUS PERFORMER                                                                ","ACTEUR, COMEDIEN ET INTERPRETE DE CIRQUE                                                            "  ],
        ["ART/CULTURE",25,15,"A","AGENT, SPORTS/ENTERTAINMENT                                                                         ","AGENT, SPORTS/DIVERTISSEMENT                                                                        "  ],
        ["ART/CULTURE",25,20,"A","ANNOUNCER/BROADCASTER                                                                               ","CHEF D’ANTENNE/DIFFUSEUR                                                                            "  ],
        ["ART/CULTURE",25,30,"A","ARCHIVIST                                                                                           ","ARCHIVISTE                                                                                          "  ],
        ["ART/CULTURE",25,40,"A","ARTISAN/CRAFTSPERSON                                                                                ","ARTISAN                                                                                             "  ],
        ["ART/CULTURE",25,50,"A","AUDIO/VIDEO RECORDING TECHNICIAN                                                                    ","TECHNICIEN, ENREGISTREMENTS AUDIO/VIDEO                                                             "  ],
        ["ART/CULTURE",25,60,"A","AUTHOR AND WRITER EXCEPT TECHNICAL                                                                  ","AUTEUR ET ECRIVAIN, SAUF TECHNIQUE                                                                  "  ],
        ["ART/CULTURE",25,70,"A","BROADCAST TECHNICIAN                                                                                ","TECHNICIEN EN RADIOTELEDIFFUSION                                                                    "  ],
        ["ART/CULTURE",25,80,"A","CONDUCTOR/COMPOSER/ARRANGER                                                                         ","CHEF D’ORCHESTRE/COMPOSITEUR/ARRANGEUR                                                              "  ],
        ["ART/CULTURE",25,90,"A","CONSERVATOR/CURATOR                                                                                 ","RESTAURATEUR/CONSERVATEUR                                                                           "  ],
        ["ART/CULTURE",25,100,"A","DANCER                                                                                              ","DANCEUR                                                                                             "  ],
        ["ART/CULTURE",25,110,"A","EDITOR                                                                                              ","EDITEUR                                                                                             "  ],
        ["ART/CULTURE",25,120,"A","FILM/BROADCAST ASSISTANT AND OPERATOR                                                               ","ASSIST. ET OPERATEUR DE CINEMA/TELEDIFF.                                                            "  ],
        ["ART/CULTURE",25,130,"A","FILM/VIDEO CAMERA OPERATOR                                                                          ","OPERATEUR DE CAMERA                                                                                 "  ],
        ["ART/CULTURE",25,140,"A","GRAPHIC ARTS TECHNICIAN                                                                             ","TECHNICIEN EN ARTS GRAPHIQUES                                                                       "  ],
        ["ART/CULTURE",25,150,"A","GRAPHIC DESIGNER/ILLUSTRATOR                                                                        ","GRAPHISTES/ILLUSTRATEUR                                                                             "  ],
        ["ART/CULTURE",25,160,"A","INFLUENCER/MODEL                                                                                    ","INFLUENCEUR/MODELE                                                                                  "  ],
        ["ART/CULTURE",25,170,"A","INTERIOR DESIGNER/INTERIOR DECORATOR                                                                ","DESIGNER/DECORATEUR D’INTERIEUR                                                                     "  ],
        ["ART/CULTURE",25,180,"A","JOURNALIST                                                                                          ","JOURNALISTE                                                                                         "  ],
        ["ART/CULTURE",25,190,"A","LIBRARIAN                                                                                           ","BIBLIOTHECAIRE                                                                                      "  ],
        ["ART/CULTURE",25,200,"A","LIBRARY/PUBLIC ARCHIVE TECHNICIAN                                                                   ","TECHN. DE BIBLIOTH./ARCHIVES PUBLIQUES                                                              "  ],
        ["ART/CULTURE",25,210,"A","MANAGER, LIBRARY/MUSEUM/ART GALLERY                                                                 ","DIRECT. DE BIBLIOTH./MUSEE/GALERIE D’ART                                                            "  ],
        ["ART/CULTURE",25,215,"A","MANAGER, SPORTS/ENTERTAINMENT                                                                       ","DIRECTEUR, SPORTS/DIVERTISSEMENT                                                                    "  ],
        ["ART/CULTURE",25,220,"A","MGR, PUBLISHING/FILM/BROADCAST/PERF ARTS                                                            ","DIRECT., EDIT./CINEMA/DIFF./SPECTACLES                                                              "  ],
        ["ART/CULTURE",25,230,"A","MUSEUM REGISTRAR/RESTORER/INTERPRETER                                                               ","REGISTRAIRE/RESTAURAT./INTERPR. DE MUSEE                                                            "  ],
        ["ART/CULTURE",25,240,"A","MUSICIAN/SINGER                                                                                     ","MUSICIEN/CHANTEUR                                                                                   "  ],
        ["ART/CULTURE",25,250,"A","PAINTER/SCULPTOR/VISUAL ARTIST                                                                      ","PEINTRE/SCULPTEUR/ARTISTE, ARTS VISUELS                                                             "  ],
        ["ART/CULTURE",25,260,"A","PHOTOGRAPHER                                                                                        ","PHOTOGRAPHE                                                                                         "  ],
        ["ART/CULTURE",25,270,"A","PHOTOGRAPHY/PERFORMING ARTS WORKER                                                                  ","TRAVAILLEUR EN PHOTOGRAPHIE/SPECTACLES                                                              "  ],
        ["ART/CULTURE",25,280,"A","PRODUCER/DIRECTOR/CHOREOGRAPHER                                                                     ","PRODUCTEUR/DIRECTEUR/CHOREGRAPHE                                                                    "  ],
        ["ART/CULTURE",25,285,"A","PROJECT/CHANGE MANAGER-ARTS AND CULTURE                                                             ","DIR. PROJET/CHANGEMENT–ARTS ET CULTURE                                                              "  ],
        ["ART/CULTURE",25,290,"A","TECHNICAL WRITER                                                                                    ","REDACTEUR TECHNIQUE                                                                                 "  ],
        ["ART/CULTURE",25,300,"A","TEXTILE/LEATHER/FUR PATTERNMAKER                                                                    ","PATRONISTE                                                                                          "  ],
        ["ART/CULTURE",25,310,"A","THEATRE/FASHION/EXHIBIT DESIGNER                                                                    ","SCENOGRAPHE/MODELISTE/DESIGNER D’EXPOS.                                                             "  ],
        ["ART/CULTURE",25,320,"A","TRANSLATOR/TERMINOLOGIST/INTERPRETER                                                                ","TRADUCTEUR/TERMINOLOGUE/INTERPRETE                                                                  "  ]
]

module.exports = data



